
.PHONY: all copy

all:
	./domains.r
	./game_types.r
	./payments.r
	./revenue.r
	./downloads.r
	./expenses.r



copy:
	mkdir -p ../../static/images/blog/store_aug
	cp *.png ../../static/images/blog/store_aug
