blank_issues_enabled: false

contact_links:
  - name: Customer Support
    url: https://itch.io/support
    about: |
      The issue tracker is not for account-specific or payment customer support.
      Our support team needs to keep track of support requests in a centralized place
      to work most effectively, and we are unable to verify who you are on a
      third-party platform like GitHub. To receive account support, you must contact
      us through our support page.
  - name: Community Support
    url: https://itch.io/board/10023/questions-support
    about: |
      Get help from the itch.io community. Have a quick question or issue,
      other members of the community can assist you in finding an answer. If
      you need to specifically contact itch.io staff you will need to contact support.
  - name: Discord
    url: https://discord.com/servers/itchio-98142307840200704
    about: Get help from the itch.io community on the official itch.io Discord server.


contributing:
  - name: Contributing Guide
    url: https://github.com/itchio/itch.io/blob/master/CONTRIBUTING.md
    about: Please review the contributing guide before opening an issue.
